require 'telescope'.load_extension('project')
-- require 'telescope'.setup {
--   extensions = {
--     project = {
--       base_dirs = {
--         'D:\\CODE\\React\\photoly',
--         {path = 'D:\\CODE\\React\\photoly'}
--       },
--       hidden_files = true
--     }
--   }
-- }
